# Generated by Django 6.0.5 on 2026-06-19 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='producto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('calle', models.CharField(blank=True, max_length=50)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('entreCalles', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('codigoPostal', models.IntegerField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
